name: HardcoreThreeLives
main: com.example.hardcorethreelives.HardcoreThreeLives
version: 1.0.0
api-version: 1.21
author: Robin
description: Hardcore met 3 kansen en daarna elke death een tempban.

commands:
  lives:
    description: Bekijk hoeveel levens je nog hebt.
    usage: /lives
  resetlives:
    description: Reset het aantal deaths van een speler (alleen voor operators).
    usage: /resetlives <speler>
  hardcore:
    description: Beheercommands voor HardcoreThreeLives.
    usage: /hardcore reload
